### PR TITLE
Bump version to v2.8.1

### PR DESCRIPTION
**Pull request by xela-95**
Bump version to v2.8.1

Closes #49 

CC @traversaro 

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Review by traversaro — APPROVED** [review]

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by traversaro** [comment]
Thanks @xela-95 !

**Comment by traversaro** [comment]
Two comments (mainly for the future):
* Please update descriptive names for PRs, not just "Update meta.yaml" that then is not useful when looking for old PRs
* As mentioned by the checklist, always run `@conda-forge-admin, please rerender`

Thanks!

**Comment by xela-95** [comment]
> Two comments (mainly for the future):
> 
> * Please update descriptive names for PRs, not just "Update meta.yaml" that then is not useful when looking for old PRs
> * As mentioned by the checklist, always run `@conda-forge-admin, please rerender`
> 
> Thanks!

Right thanks!

**Pull request merged**
